from django.conf import settings

TRADUCOES = {
  'en': {
    'acessar': 'View in the website',
    'acessar a administração': "Django administration",
    'acessar o projeto': 'Access the project',
    'ações': 'ACTIONS',
    'análise': 'ANALYSIS',
    'ao fechar esta aba, este processamento será finalizado!': 'The current news processing will stop if you close this tab!',
    'aviso': 'Warning',
    'carregar outras notícias': 'Load other news',
    'carregar processamento': 'Load previous processed data',
    'classificadores': 'CLASSIFIERS',
    'coletar dados': 'Start the news gathering',
    'coleta de notícias': 'News gathering',
    'deletar': 'Delete',
    'executar processamento de notícias': 'Begin execution',
    'executar processamento': 'Begin execution',
    'erro': 'Error',
    'fechar': 'Close',
    'histórico de processamento': 'Execution history',
    'id processamento': 'Execution ID',
    'insira a id de processamento (opcional)': 'Insert the previous processing ID (optional)',
    'matriz de confusão - modelo': 'Confusion matrix - model',
    'nenhum projeto foi encontrado!': 'No project was found!',
    'notícias': 'News',
    'notícia': 'News',
    'notícias relevantes': 'Relevant news',
    'notícias sobre outros assuntos': 'Other news (outside the keyword context)',
    'notícias gravadas (processadas)': 'Recorded news (filtered)',
    'o projeto não possui sites vinculados!': 'This project has no linked news websites!',
    'o projeto não possui palavras-chaves vinculadas!': 'This project has no linked keywords!',
    'página de coleta': 'Home page',
    'palavra-chave': 'Keywords',
    'pontuação ref.real': 'Score with related news',
    'pontuação ref.não real': 'Score with unrelated news',
    'previsão': 'Forecast',
    'projetos': 'Projects',
    'salvar as notícias automaticamente?': 'Automatically save the news?',
    'título': 'Title',
    'ver histórico de processamento': 'Access the execution history',
    'coleta': 'News gathering',
    'sim': 'Yes',
    'não': 'No',
    'estados': 'Country States',
    'cidades': 'Cities',
    'cidade': 'City',
    'estado': 'State',
    'palavras-chaves': 'keywords',
    'campos': 'Fields',
    'apenas brasil': 'Brazil only',
    'nome': 'Name',
    'estado': 'State',
    'país': 'Country',
    'código do ibge': 'Unique ID',
    'uf': 'Short name',
    'região': 'Region',
    'acessar página interna': 'access the internal url',
    'tipo de paginação': 'Pagination type',
    'sites de notícias': 'News websites',
    'notícias coletadas': 'Recorded news',
    'sem notícia': 'No news found',
    'estrutura inicial de lista de notícias': 'Initial structure for the news websites (html)',
    'estrutura de lista de notícias': 'News list structure (html)',
    'projeto': 'Project',
    'estrutura inicial de notícias': 'Initial structure for the news websites',
    'estrutura de notícia': 'News list structure',
    'separado por virgula': 'Separated by comma',
    'sentença': 'phrase',
    'data de início': 'Start date',
    'cadastrar sem acentos': 'Without accents',
    'tipo': 'Type',
    'ativo': 'Active',
    'caminho': 'Path',
    'sem paginação': 'No pagination',
    'url simples': 'Pagination by url',
    'url via backend': 'Pagination by backend request',
    'elemento html': 'Pagination by html tag',
    'atributo na lista de notícias': 'Attribute in news list',
    'caminho para a subtag': 'Subtag Path',
    'campo': 'Field',
    'estrutura inicial': 'Initial structure',
    'tipo de página': 'Page type',
    'descrição': 'Description',
    'conteúdo': 'Content',
    'inserido em': 'Created at',
    'data da coleta': 'Created at',
    'caminho da imagem': 'Image local path',
    'imagem': 'Image',
    'data da notícia': 'News date',
    'dia': 'Day',
    'mês': 'Month',
    'ano': 'Year',
    'site sem notícias': 'No news found',
    'erro na paginação, loop: ': 'Pagination error, loop iteration: ',
    'site (página) não encontrada!': 'Website (page) not found!',
    'erro no requisição da lista de noticias': 'Problem during the request for the news list',
    'verdadeiro positivo (vp)': 'True positive (TP)',
    'verdadeiro negativo (vn)': 'True negative (TN)',
    'falso positivo (fp)': 'False positive (FP)',
    'falso negativo (fn)': 'False negative (FN)',
    'notícias processadas': 'Processed news',
    'resultado do processamento': 'Results',
    'localização': 'Location',
    'acurácia': 'Accuracy',
    'precisão': 'Precision',
    'quantidade de notícias': 'News quantity',
    'criado em': 'Created at',
    'classificação de modelos': 'Classification Algorithms',
    'matriz de confusão': 'Confusion matrix',
    'modelo': 'Model'

  }
}

def traduzir(frase_original):
  idioma = settings.LANGUAGE_CODE
  frase = frase_original.lower()
  
  if idioma == 'pt-br':
    return frase_original

  if idioma not in TRADUCOES:
    return frase_original
  
  if frase not in TRADUCOES[idioma]:
    return frase_original
  
  return TRADUCOES[idioma][frase]

