# Generated by Django 4.1.7 on 2023-08-16 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Cadastrar sem acentos', max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=355)),
                ('latitude', models.CharField(blank=True, max_length=30)),
                ('longitude', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConteudoNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=300)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('dia', models.CharField(blank=True, max_length=20, null=True)),
                ('mes', models.CharField(blank=True, max_length=20, null=True)),
                ('ano', models.CharField(blank=True, max_length=20, null=True)),
                ('data_formatada', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem', models.CharField(blank=True, max_length=355, null=True)),
                ('url', models.CharField(blank=True, max_length=355, null=True)),
                ('caminho_img_local', models.CharField(blank=True, max_length=355, null=True)),
                ('id_coleta', models.CharField(blank=True, max_length=100, null=True)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('cidade', models.ForeignKey(db_column='cidade', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coleta.cidade', to_field='ibge')),
            ],
            options={
                'verbose_name_plural': 'Notícias coletadas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2, unique=True)),
                ('regiao', models.CharField(choices=[('NORTE', 'Região Norte'), ('NORDESTE', 'Região Nordeste'), ('CENTRO-OESTE', 'Região Centro-Oeste'), ('SUDESTE', 'Região Sudeste'), ('SUL', 'Região Sul')], max_length=15)),
            ],
            options={
                'ordering': ['uf'],
            },
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra_chave', models.CharField(max_length=255)),
                ('data_inicio', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('ativo', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('palavras_chaves', models.ManyToManyField(blank=True, to='coleta.palavrachave')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TreinamentoSentencas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentencas', to='coleta.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='SiteNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('acessar_pagina_interna', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('tipo_paginacao', models.CharField(blank=True, choices=[('', 'Sem paginação'), ('url', 'Url simples'), ('url_backend', 'Url via backend'), ('elemento_html', 'Elemento html')], max_length=100, null=True)),
                ('json_args', models.TextField(blank=True, null=True)),
                ('req_response', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.ForeignKey(db_column='uf', on_delete=django.db.models.deletion.DO_NOTHING, to='coleta.estado', to_field='uf')),
            ],
            options={
                'verbose_name_plural': 'Sites de notícias',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='sites',
            field=models.ManyToManyField(blank=True, to='coleta.sitenoticia'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_coleta', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=355, null=True)),
                ('titulo', models.CharField(blank=True, max_length=355, null=True)),
                ('erro', models.TextField(blank=True, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True)),
                ('conteudo_noticia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coleta.conteudonoticia')),
                ('palavra_chave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coleta.palavrachave')),
                ('projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coleta.projeto')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coleta.sitenoticia')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LocalInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentenca', models.TextField(help_text='Separado por virgula')),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_interessante', to='coleta.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='InitEstruturaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('caminho', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.sitenoticia')),
            ],
            options={
                'verbose_name_plural': 'Estrutura inicial de lista de notícias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EstruturaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('caminho', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('tipo_pagina', models.CharField(choices=[('lista', 'Atributo na lista de notícias')], max_length=100)),
                ('subtag', models.CharField(blank=True, max_length=255, null=True)),
                ('subtag_caminho', models.CharField(blank=True, max_length=255, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.campo')),
                ('inicio_estrutura_noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.initestruturanoticia')),
            ],
            options={
                'verbose_name_plural': 'Estrutura de lista de notícias',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='conteudonoticia',
            name='estado',
            field=models.ForeignKey(db_column='estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coleta.estado', to_field='uf'),
        ),
        migrations.AddField(
            model_name='conteudonoticia',
            name='inicio_estrutura_noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.initestruturanoticia'),
        ),
        migrations.AddField(
            model_name='conteudonoticia',
            name='palavras_chaves',
            field=models.ManyToManyField(related_name='palavra_por_noticia', to='coleta.palavrachave'),
        ),
        migrations.AddField(
            model_name='conteudonoticia',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.projeto'),
        ),
        migrations.AddField(
            model_name='conteudonoticia',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.sitenoticia'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(db_column='uf', on_delete=django.db.models.deletion.DO_NOTHING, to='coleta.estado', to_field='uf'),
        ),
    ]
