# Generated by Django 4.1.7 on 2023-03-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data', models.DateTimeField(verbose_name='date published')),
                ('ativo', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
            ],
        ),
    ]
