# Generated by Django 4.1.7 on 2023-08-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreinamentoSentencas',
        ),
    ]
