# Generated by Django 4.1.7 on 2023-03-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0004_alter_projeto_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringBusca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra_chave', models.CharField(max_length=255)),
                ('data_inicio', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='data',
            new_name='data_inicio',
        ),
    ]
