# Generated by Django 4.1.7 on 2023-03-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0005_stringbusca_rename_data_projeto_data_inicio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StringBusca',
            new_name='PalavraChave',
        ),
        migrations.AlterModelTable(
            name='palavrachave',
            table='string_busca',
        ),
    ]
