# Generated by Django 4.1.7 on 2023-03-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0006_rename_stringbusca_palavrachave_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projeto',
            table='projeto',
        ),
    ]
