# Generated by Django 4.1.7 on 2023-03-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0007_alter_projeto_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('acessar_pagina_interna', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
                ('tipo_paginacao', models.CharField(blank=True, choices=[('url_backend', 'Url via backend'), ('elemento_html', 'Elemento html')], max_length=100, null=True)),
                ('req_response', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
