# Generated by Django 4.1.7 on 2023-03-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0008_sitenoticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitenoticia',
            name='json_args',
            field=models.TextField(blank=True, null=True),
        ),
    ]
