# Generated by Django 4.1.7 on 2023-03-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0010_sitenoticia_palavras_chaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenoticia',
            name='palavras_chaves',
            field=models.ManyToManyField(null=True, to='coleta.palavrachave'),
        ),
    ]
