# Generated by Django 4.1.7 on 2023-03-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0012_alter_sitenoticia_palavras_chaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitenoticia',
            name='palavras_chaves',
        ),
        migrations.AddField(
            model_name='projeto',
            name='sites',
            field=models.ManyToManyField(blank=True, null=True, to='coleta.sitenoticia'),
        ),
    ]
