# Generated by Django 4.1.7 on 2023-03-19 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0013_remove_sitenoticia_palavras_chaves_projeto_sites'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sitenoticia',
            table='pag_jornal',
        ),
    ]
