# Generated by Django 4.1.7 on 2023-03-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0015_alter_projeto_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='palavras_chaves',
            field=models.ManyToManyField(blank=True, to='coleta.palavrachave'),
        ),
    ]
