# Generated by Django 4.1.7 on 2023-03-19 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0016_projeto_palavras_chaves'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='palavrachave',
            table=None,
        ),
        migrations.AlterModelTable(
            name='projeto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sitenoticia',
            table=None,
        ),
        migrations.CreateModel(
            name='InitEstruturaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('caminho', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.sitenoticia')),
            ],
        ),
    ]
