# Generated by Django 4.1.7 on 2023-03-19 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0017_alter_palavrachave_table_alter_projeto_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstruturaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('caminho', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('tipo_pagina', models.CharField(max_length=100)),
                ('subtag', models.CharField(blank=True, max_length=255, null=True)),
                ('subtag_caminho', models.CharField(blank=True, max_length=255, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.campo')),
                ('inicio_estrutura_noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.initestruturanoticia')),
            ],
        ),
    ]
