# Generated by Django 4.1.7 on 2023-03-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0018_campo_estruturanoticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estruturanoticia',
            name='tipo_pagina',
            field=models.CharField(choices=[('lista', 'Atributo na lista de notícias'), ('pagina', 'Atributo na página individual')], max_length=100),
        ),
    ]
