# Generated by Django 4.1.7 on 2023-04-04 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0019_alter_estruturanoticia_tipo_pagina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campo',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='estruturanoticia',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='initestruturanoticia',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='palavrachave',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sitenoticia',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='sitenoticia',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitenoticia',
            name='tipo_paginacao',
            field=models.CharField(blank=True, choices=[('', 'Sem paginação'), ('url', 'Url simples'), ('url_backend', 'Url via backend'), ('elemento_html', 'Elemento html')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ConteudoNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('conteudo', models.TextField(blank=True)),
                ('dia', models.CharField(blank=True, max_length=20)),
                ('mes', models.CharField(blank=True, max_length=20)),
                ('ano', models.CharField(blank=True, max_length=20)),
                ('data_formatada', models.CharField(blank=True, max_length=100)),
                ('localizacao', models.CharField(blank=True, max_length=100)),
                ('imagem', models.CharField(blank=True, max_length=355)),
                ('url', models.CharField(blank=True, max_length=355)),
                ('caminho_img_local', models.CharField(blank=True, max_length=355)),
                ('id_coleta', models.CharField(blank=True, max_length=100)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('inicio_estrutura_noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.initestruturanoticia')),
                ('palavras_chaves', models.ManyToManyField(to='coleta.palavrachave')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.projeto')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.sitenoticia')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
