# Generated by Django 4.1.7 on 2023-05-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0022_rename_logs_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(help_text='Cadastrar sem acentos', max_length=255),
        ),
        migrations.AlterField(
            model_name='estruturanoticia',
            name='tipo_pagina',
            field=models.CharField(choices=[('lista', 'Atributo na lista de notícias')], max_length=100),
        ),
    ]
