# Generated by Django 4.1.7 on 2023-09-18 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coleta', '0002_delete_treinamentosentencas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoProcessamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_processamento', models.CharField(max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acuracia', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('precisao', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('recall', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('f1_score', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.projeto')),
            ],
            options={
                'ordering': ['id_processamento', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaReferenciaProcessamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticia_real', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=3)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coleta.conteudonoticia')),
                ('processamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processamento.resultadoprocessamento')),
            ],
        ),
        migrations.CreateModel(
            name='NoticiaProcessada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField(null=True)),
                ('cidade', models.TextField(null=True)),
                ('localizacao', models.TextField(null=True)),
                ('palavras_chaves', models.TextField()),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.conteudonoticia')),
            ],
            options={
                'verbose_name_plural': 'Notícias processadas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30)),
                ('acuracia', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('precisao', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('recall', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('f1_score', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('tipo_metrica', models.CharField(choices=[('REAL', 'Rótulos reais (manuais)'), ('CALCULADA', 'Rótulos calculados')], max_length=15, null=True)),
                ('processamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processamento.resultadoprocessamento')),
            ],
            options={
                'ordering': ['processamento'],
            },
        ),
    ]
