# Generated by Django 4.1.7 on 2023-08-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coleta', '0002_delete_treinamentosentencas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoProcessamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_processamento', models.CharField(max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('limiar', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('margem', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('media_diff_quadrada', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('desvio_padrao', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('limiar_ajustado', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('taxa_acertos', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('noticias_referencias', models.ManyToManyField(to='coleta.conteudonoticia')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.projeto')),
            ],
            options={
                'ordering': ['id_processamento', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaProcessada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField(null=True)),
                ('cidade', models.TextField(null=True)),
                ('localizacao', models.TextField(null=True)),
                ('palavras_chaves', models.TextField()),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.conteudonoticia')),
            ],
            options={
                'verbose_name_plural': 'Notícias processadas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30)),
                ('acuracia', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('precisao', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('recall', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('f1_score', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('processamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processamento.resultadoprocessamento')),
            ],
            options={
                'ordering': ['processamento'],
            },
        ),
        migrations.CreateModel(
            name='ProcessamentoSbert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.DecimalField(decimal_places=4, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticia_testada', to='coleta.conteudonoticia')),
                ('noticia_referencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticia_referencia', to='coleta.conteudonoticia')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.projeto')),
            ],
            options={
                'verbose_name_plural': 'Processamento SBERT de notícias',
                'ordering': ['projeto', 'noticia', 'noticia_referencia'],
                'unique_together': {('noticia', 'noticia_referencia')},
            },
        ),
        migrations.CreateModel(
            name='NoticiaParecida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticia_processada_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticia_processada_a', to='processamento.noticiaprocessada')),
                ('noticia_processada_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticia_processada_b', to='processamento.noticiaprocessada')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.projeto')),
            ],
            options={
                'verbose_name_plural': 'Notícias parecidas',
                'ordering': ['id'],
                'unique_together': {('noticia_processada_a', 'noticia_processada_b')},
            },
        ),
    ]
