# Generated by Django 4.1.7 on 2024-03-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoProcessamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_processamento', models.CharField(max_length=30, verbose_name='Execution ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('acuracia', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Accuracy')),
                ('precisao', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Precision')),
                ('recall', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('f1_score', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('vp', models.IntegerField(null=True, verbose_name='True positive (TP)')),
                ('vn', models.IntegerField(null=True, verbose_name='True negative (TN)')),
                ('fp', models.IntegerField(null=True, verbose_name='False positive (FP)')),
                ('fn', models.IntegerField(null=True, verbose_name='False negative (FN)')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.projeto', verbose_name='Project')),
            ],
            options={
                'verbose_name_plural': 'Results',
                'ordering': ['id_processamento', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaResultadoProcessamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo_real', models.CharField(max_length=10)),
                ('rotulo_calculado', models.CharField(max_length=10)),
                ('pontuacao_real', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('pontuacao_nao_real', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('classificadores', models.TextField(blank=True, max_length=200, null=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coleta.conteudonoticia')),
                ('processamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processamento.resultadoprocessamento')),
            ],
        ),
        migrations.CreateModel(
            name='NoticiaReferenciaProcessamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticia_real', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=3)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coleta.conteudonoticia')),
                ('processamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processamento.resultadoprocessamento')),
            ],
        ),
        migrations.CreateModel(
            name='NoticiaProcessada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField(null=True, verbose_name='State')),
                ('cidade', models.TextField(null=True, verbose_name='City')),
                ('localizacao', models.TextField(null=True, verbose_name='Location')),
                ('palavras_chaves', models.TextField(verbose_name='Palavras-chaves')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleta.conteudonoticia', verbose_name='News')),
            ],
            options={
                'verbose_name_plural': 'Processed news',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30, verbose_name='Model')),
                ('acuracia', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Accuracy')),
                ('precisao', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Precision')),
                ('recall', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('f1_score', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('qtd_noticias', models.IntegerField(null=True, verbose_name='News quantity')),
                ('vp', models.IntegerField(null=True, verbose_name='True positive (TP)')),
                ('vn', models.IntegerField(null=True, verbose_name='True negative (TN)')),
                ('fp', models.IntegerField(null=True, verbose_name='False positive (FP)')),
                ('fn', models.IntegerField(null=True, verbose_name='False negative (FN)')),
                ('matriz_confusao', models.TextField(null=True, verbose_name='Confusion matrix')),
                ('processamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processamento.resultadoprocessamento', verbose_name='Execution')),
                ('projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coleta.projeto', verbose_name='Project')),
            ],
            options={
                'verbose_name_plural': 'Classification Algorithms',
                'ordering': ['processamento', 'projeto'],
            },
        ),
    ]
