# Generated by Django 4.1.7 on 2023-09-18 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0002_delete_treinamentosentencas'),
        ('processamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaResultadoProcessamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo_real', models.CharField(max_length=10)),
                ('rotulo_calculado', models.CharField(max_length=10)),
                ('pontuacao_real', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('pontuacao_nao_real', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coleta.conteudonoticia')),
                ('processamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processamento.resultadoprocessamento')),
            ],
        ),
    ]
