# Generated by Django 4.1.7 on 2023-08-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadoprocessamento',
            old_name='taxa_acertos',
            new_name='acuracia',
        ),
        migrations.AddField(
            model_name='resultadoprocessamento',
            name='f1_score',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='resultadoprocessamento',
            name='precisao',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='resultadoprocessamento',
            name='recall',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
