# Generated by Django 4.1.7 on 2023-09-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0002_noticiaresultadoprocessamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiaresultadoprocessamento',
            name='classificadores',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
