# Generated by Django 4.1.7 on 2023-08-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0002_rename_taxa_acertos_resultadoprocessamento_acuracia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacaomodelo',
            name='tipo_metrica',
            field=models.CharField(choices=[('REAL', 'Rótulos reais (manuais)'), ('CALCULADA', 'Rótulos calculados')], max_length=15, null=True),
        ),
    ]
