# Generated by Django 4.1.7 on 2023-09-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0002_delete_treinamentosentencas'),
        ('processamento', '0003_noticiaresultadoprocessamento_classificadores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificacaomodelo',
            options={'ordering': ['processamento', 'projeto']},
        ),
        migrations.RemoveField(
            model_name='classificacaomodelo',
            name='tipo_metrica',
        ),
        migrations.AddField(
            model_name='classificacaomodelo',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coleta.projeto'),
        ),
        migrations.AddField(
            model_name='classificacaomodelo',
            name='qtd_noticias',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='classificacaomodelo',
            name='processamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processamento.resultadoprocessamento'),
        ),
    ]
